#!/bin/sh

# PROVIDE: bhyved
# REQUIRE: DAEMON
# BEFORE: LOGIN cleanvar sshd zfs
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="bhyved"
desc="bhyve management daemon"
rcvar="bhyved_enable"
command="/usr/local/sbin/${name}"
pidfile="/var/run/bhyved.pid"
extra_commands="reload"
required_modules="vmm"

load_rc_config $name
run_rc_command "$1"
