.Dd Apr 8, 2024
.Dt BMD.CONF 5
.Os
.Sh NAME
.Nm bmd.conf
.Nd configuration file for
.Xr bmd 8
.Sh DESCRIPTION
A
.Xr bmd 8
configuration file consists of 3 types of sections, global, vm, template.
The global section defines
.Xr bmd 8
configurations and global variables. See Global Parameters for detail.
The global section must be written in a file which root privileged user owns.
If the other user owns the file, the global section is parsed but ignored.
Each Vm section defines VM configurations and vm scope variables.
The templates are part of VM configurations common to multiple VMs.
It is applied with optional arguments from a vm section or a template section.
The same template cannot be applied more than once.
Each template argument can take a default value in case it is omitted.
The default value is written following the
.Qq \&=
after the argument.

The section starts with its type name. The vm and template sections are
followed by name. Vm names are unique identifier for each vm section and
template names are also unique identifier for each template sections.

In each sections, configurations are written in
.Qo
key = value;
.Qs
like C language
statement. If a key takes multiple value, use
.Qq +=
operator or write multiple
values separated by a comma
.Sq \&, .

The general syntax is:
.Bd -literal -offset indent
global {
	global_parameter = "value1";
	global_parameter = "value2";
	...
}
template tmplA(param = "sample") {
	vm_parameter = "value1";
	vm_parameter = $param;
	...
}
vm hostB {
	vm_parameter = "value1";
	vm_parameter = "value2";
	...
}
.Ed
.Ss Global Parameters
.Bl -tag -width cmd_socket_path
.It Cm cmd_socket_path = Ar pathname;
Unix domain socket path. The default value is
.Qq Pa /var/run/bmd.sock .
.It Cm cmd_socket_mode = Ar mode;
File mode bits in octal number. The default value is
.Qq 0600.
.It Cm vars_directory = Ar dirname;
The directory to write UEFI variables. The default value is
.Qq Pa /usr/local/var/cache/bmd .
.It Cm nmdm_offset = Ar noffset;
The offset of auto assigned nmdm number. The default value is
.Qq 200 .
.It Cm pid_file = Ar filepath;
The file to write
.Xr bmd 8
pid. The default value is
.Qq Pa /var/run/bmd.pid .
.El
.Ss Vm Parameters
.Bl -tag -width installcmd
.It Cm boot = Ar no | yes | oneshot | always ;
.Bl -tag -width oneshot
.It Cm no
Do not boot at
.Xr bmd 8
starts. This is the default.
.It Cm yes
Boot at
.Xr bmd 8
starts or reloads configurations.
.It Cm oneshot
Boot at
.Xr bmd 8
starts and never reboots.
.It Cm always
Boot at
.Xr bmd 8
starts or reloads configurations. And always reboots VM after successful
shutdown. If VM exits with an error,
.Xr bmd 8
does not reboot again.
.El
.It Cm boot_delay = Ar delay_second;
Boot delay in seconds. The default value is
.Qq 0 .
.It Cm comport = Ar com_device;
Specify com1 port device (e.g. /dev/nmdm0B).
.Qq auto
assigns a nmdm device
automatically.
.It Cm debug_port = Ar port_number;
Gdb debug port.
.It Cm disk = (+=) Oo Ar type : Oc Ar filename ;
Type is one of
.Qq nvme ,
.Qq ahci ,
.Qq ahci-hd ,
.Qq virtio-blk
or can be omitted
to specify the default type
.Qq virtio-blk .
Filename is disk image filename(e.g. /var/images/vm-disk-0) or device file
(e.g. /dev/zvol/zpool/vm-disk-1).
.It Cm err_logfile = Ar filename;
Log filename of bhyve messages.
.It Cm graphics = Ar yes | no;
Set
.Qq yes
to use frame buffer device. The default is
.Qq no .
.It Cm graphics_listen = Ar port_num;
Vnc port number. The default value is
.Qq 5900 .
.It Cm graphics_password = Ar password;
Password for vnc access. This is not set by default.
.It Cm graphics_res = Ar width x height;
Vnc resolution. The default value is
.Qq 1280x720 .
.It Cm graphics_vga = Ar on | off | io;
Vga conf of bhyve. The default is
.Qq io .
.It Cm graphics_wait = Ar yes | no;
Wait for vnc connection before booting. The default is
.Qq no .
.It Cm hostbridge = Ar standard | amd;
Hostbridge device. The default is
.Qq standard .
.It Cm install = Ar yes | no;
Set
.Qq yes
to boot from ISO. The install mode VM will never restart, it always quits the
bhyve execution. After the installation has finished,
change the configuration to
.Qq no .
The default is
.Qq no .
.It Cm installcmd = Ar install_cmd;
Install script for grub-bhyve. Setting
.Qq auto
inspects iso image.
e.g.
.Qo
kopenbsd -h com0 (cd0)/6.9/amd64/bsd.rd
.Qs
.It Cm iso = (+=) Ar image_filepath;
ISO image filename.
.It Cm keymap = Ar keymap;
Keymap for vnc.
.It Cm loadcmd = Ar load_cmd;
Boot script for grub-bhyve. Setting
.Qq auto
inspects disk image.
e.g.
.Qo
kopenbsd -h com0 -r sd0a (hd0,gpt4)/bsd
.Qs
.It Cm loader = Ar bhyveload | grub | uefi;
Specify boot loader. This parameter is mandatory.
.It Cm loader_timeout = Ar timeout_sec;
Loader timeout in seconds. If set to 0 or negative value, timeout is disabled.
The default value is
.Qq 15 .
.It Cm bhyve_env = (+=) Ar Environment_definition;
Specify an environment variable for the bhyve process. Note that
.Ar Environment_definition
must contain a equal character '='. It must be escaped by a backslash or
enclosed in double quotes. e.g.
.Qq BHYVE_TMPDIR=/tmp
.It Cm bhyveload_loader = Ar OS_loader_path;
Specify the path to the OS loader. It is passed with
.Qq -l
to the bhyveload.
If omitted, the default OS loader
.Qq Pa /boot/userboot.so
is used.
.It Cm bhyveload_env = (+=) Ar Environment_definition;
Specify an environment variable for the FreeBSD boot loader.
It is passed with
.Qq -e
to the bhyveload. Note that
.Ar Environment_definition
must contain a equal character
.Sq = .
It must be escaped by a backslash or
enclosed in double quotes. e.g.
.Qq machdep.hyperthreading_allowed=0
.It Xo
.Cm memory = Ar memsize Ns Oo
.Sm off
.Cm K | k | M | m | G | g | T | t
.Sm on
.Oc ;
.Xc
Specify physical memory size. This parameter is mandatory.
.It Cm name = Ar vmname;
Change the virtual machine name from vm section name;
.It Cm ncpu = Ar num_sockets Op Ar :num_cores Op Ar :num_threads ;
Set the number of CPUs or CPU topology for VM. The default value is 1 for each parameters.
e.g. 1:4:2 specifies cpus=8,sockets=1,cores=4,threads=2 to the bhyve.
.It Cm cpu_pin = (+=) Ar vcpu:hostcpu;
Pin guest's virtual CPU
.Ar vcpu
to
.Ar hostcpu .
Host CPUs and guest virtual CPUs are numberd starting from 0.
The number of
.Ar vcpu
must be smaller than
.Ar ncpu
value.
The number of
.Ar hostcpu
must be smaller than
.Ar hw.ncpu
.Xr sysctl 8
value.
.It Cm network = (+=) Oo Ar type : Oc Ar bridge ;
.Ar Type
is one of
.Qq e1000 ,
.Qq virtio-net
or can be omitted to specify
the default type
.Qq virtio-net .
.Ar Bridge
is a bridge name that a tap interface
to be added. e.g.
.Qq bridge1
.It Cm owner = Ar user_name Op : Ar group_name ;
Owner of VM. The owner is permitted to control the VM via
.Xr bmdctl 8 .
If
.Ar group_name
is specified, users of
.Ar group_name
are also permitted.
The default value is as same as the file owner in which vm section is written.
Setting owner is permitted if the file owner is root privileged user or the
.Ar user_name
is as same as the file owner.
.It Cm passthru = (+=) Ar bus/slot/function;
PCI passthrough device id. e.g. 1/0/130
.It Cm reboot_on_change = Ar yes | no;
Set
.Qq yes
to force ACPI reboot if VM config file is change. The default is
.Qq no .
.It Cm stop_timeout = Ar timeout_sec;
VM exit timeout in seconds. if expired, force to kill VM. The default value is
.Qq 300 .
This timeout will never be disabled.
.It Cm tpm = Ar dev Oo : Ar version Oc | Ar type : Ar dev : Ar version ;
Specify a TPM device for the VM. The
.Ar dev
paramter is a tpm device name. e.g.
.Qq /dev/tpm0 .
Currently the
.Ar type
parameter supports
.Qq passthru
only. The default value of
.Ar version
is
.Qq 2.0 .
.It Cm utctime = Ar yes | no;
Set
.Qq yes
for RTC to keep UTC time. Set
.Qq no
for RTC to keep localtime.
The default value is
.Qq yes .
.It Cm wired_memory = Ar yes | no;
Set
.Qq yes
to wire VM memory. The default is
.Qq no .
.It Cm xhci_mouse = Ar yes | no;
Set
.Qq yes
to use xhci tablet. The default is
.Qq no .
.El
.Ss String format
Parameter values, including vm names and template names, can be single tokens
or quoted strings.
A token is any sequence of characters that are not considered special in
the syntax of the configuration file (such as a semicolon or
whitespace).
If a value contains anything more than letters, numbers, dots, dashes
and underscores, it is advisable to put quote marks around that value.
Either single or double quotes may be used.
.Pp
Special characters may be quoted by preceding them with a backslash.
Common C-style backslash character codes are also supported, including
control characters and octal or hex ASCII codes.
A backslash at the end of a line will ignore the subsequent newline and
continue the string at the start of the next line.
.Ss Variables
A string may use shell-style variable substitution.
A variable name preceded by a dollar sign, and possibly enclosed in braces,
will be replaced with the value of variable.
Variable substitution occurs in unquoted tokens or in double-quoted strings,
but not in single-quote strings.
.Pp
A variable is defined in the way that the variable name is preceded with a
dollar sign:
.Bd -literal -offset indent
$pathname = "/var/spool/vm/images";
.Ed
.Pp
Variables belongs to either global or vm scope. The global scope variables
are defined in the global section and referred in all other sections. The vm
scope variable is defined in vm sections and available for the vm
configurations. Variables in template section belongs to vm scope that applies
the template. Vm scope variables before applying templates is available in the
template. Variables defined in a template can be referred after applying the
template. The following pre-defined variables are available.
.Bl -tag -width LOCALBASE -offset indent
.It Cm LOCALBASE
The same value of LOCALBASE in compile time. (global scope)
.It Cm ID
Unique number for each individual VMs that starts from 0. (vm scope)
.It Cm NAME
Virtual machine name. (vm scope)
.It Cm OWNER
Owner name of the VM. (vm scope)
.It Cm GROUP
Group name of the VM. The default is empty string. (vm scope)
.El
.Ss Arithmetic Expansion
Like
.Xr sh 1 ,
Arithmetic expansion provides a mechanism for evaluating an arithmetic
expression:
.Pp
.D1 Li $(( Ns Ar expression Ns Li ))
.Pp
The allowed expressions are a subset of
.Xr sh 1 ,
summarized blow.
.Bl -tag -width "Variables" -offset indent
.It Values
All values are type of
.Ft long .
.It Constants
Decimal, octal (starting with
.Li 0 )
and hexadecimal (starting with
.Li 0x )
integer constants.
.It Variables
Both global and vm scope variables can be read and contain integer constants.
.It Binary operators
.Li "* / % + -"
.El
.Ss Macros
2 macros are available.
.Bl -tag -width .include
.It Cm .apply Ar template_name Op (arg1, ...), template_name2 ;
Apply the template(s) with optional arguments. This macro can be written in the
vm and template sections.
.It Cm .include Ar include_pattern ;
Include another configuration file(s). This macro must be written outside of
the sections. This is only one exception not to be written in the sections.
The
.Ar include_pattern
can contain special characters
.Sq \&* ,
.Sq \&? ,
or
.Sq \&[ ,
.Sq \&]
that matches as same as shell wildcard.
The
.Ar include_pattern
can contain global scope variable which is defined earlier than this macro.
.Sh EXAMPLES

.Bd -literal -offset indent
global {
	cmd_socket_mode = 0660;
	$imgpath = /dev/zpol/zpool/images;
	$isopath = /zpool/iso;
}

template default_disk {
	disk = ${imgpath}/${NAME};
}

template graphics {
	graphics = yes;
	graphics_port = $((5900 + ${ID}));
	xhci_mouse = yes;
}

template serial {
	comport = auto;
}

template internet {
	network = bridge0;
}

template grub_inspect {
	loader = grub;
	loadcmd = auto;
	installcmd = auto;
}

vm freebsd {
	boot = yes;
	ncpu = 2;
	memory = 2G;
	iso = ${isopath}/FreeBSD-13.2-RELEASE-amd64-disc1.iso;
	loader = bhyveload;
	.apply default_disk, serial, internet;
}

vm netbsd {
	boot = yes;
	ncpu = 2;
	memory = 2G;
	iso = ${isopath}/NetBSD-9.2-amd64.iso;
	.apply default_disk, serial, internet, grub_inspect;
}

vm openbsd {
	boot = yes;
	ncpu = 2;
	memory = 2G;
	iso = ${isopath}/OpenBSD-6.9-amd64.iso;
	.apply default_disk, serial, internet, grub_inspect;
}

vm centos {
	boot = yes;
	ncpu = 2;
	memory = 4G;
	iso = ${isopath}/CentOS-8.2.2004-x86_64-dvd1.iso;
	loader = uefi;
	.apply default_disk, internet, graphics;
}

vm ubuntu {
	boot = yes;
	ncpu = 2;
	memory = 4G;
	iso = ${isopath}/ubuntu-20.04.2.0-desktop-amd64.iso;
	loader = uefi;
	.apply default_disk, internet, graphics;
	graphics_res = 1280x720;
}

\&.include "bmd.d/*";
.Ed
.Sh SEE ALSO
.Xr bmd 8 ,
.Xr bmdctl 8
