.Dd Jul 27, 2023
.Dt BMD 8
.Os
.Sh NAME
.Nm bmd
.Nd bhyve management daemon
.Sh SYNOPSIS
.Nm
.Op Fl F
.Op Fl f Ar config_file
.Op Fl P Ar pid_file
.Op Fl p Ar plugin_directory
.Op Fl m Ar unix_domain_socket_permission
.Op Fl v
.Sh DESCRIPTION
The
.Nm
utility spawns bhyve processes according to the configuration file,
and waits for them to terminate. If a bhyve process terminates with
exit code 0 (rebooted),
.Nm
spawns the bhyve process again. The
.Nm
receives control commands from
.Xr bmdctl 8
to manage bhyve processes via unix
domain socket. See
.Xr bmdctl 8
for detail.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl F
Run in foreground.
.It Fl f Ar config_file
Specify the pathname of an alternate configuration file.
The default is
.Pa /usr/local/etc/bmd.conf .
.It Fl P Ar pid_file
Specify an alternative file in which to store the process ID.
The default is
.Pa /var/run/bmd.pid .
.It Fl p Ar plugin_directory
Specify the directory path of an alternate plugin store.
The default is
.Pa /usr/local/libexec/bmd .
.It Fl m Ar unix_domain_socket_permission
Specify the unix domain socket permission in octal number.
The default is
.Pa 0660 .
Please note that the unix domain socket path can not be changed in command
line options. See
.Xr bmd.conf 5
to change the path.
.It Fl v
Show version number.
.El
.Pp
The
.Nm
waits for control commands from
.Xr bmdctl 8
via unix domain socket. When
.Nm
receives a boot request from
.Xr bmdctl 8 ,
.Nm
reloads the configuration file to check updates for boot target. If any
updates are found, the
.Nm
adopts the updated configuration.
.Sh SIGNAL HANDLING
.Nm
deals with the following signals:
.Pp
.Bl -tag -width SIGTERM -compact
.It SIGTERM
Send SIGTERM to all bhyve processes and wait for them to terminate,
then quit the daemon.
.It SIGHUP
Reload the configuration file.
.El
.Sh PLUGINS
.Nm
loads plugins on start up. Plugins extend the functionality of
.Nm .
And also add configuration parameters for extended functionality if necessary.
.Sh FILES
.Bl -tag -width /usr/local/var/cache/bmd -compact
.It Pa /var/run/bmd.pid
Pid file
.It Pa /var/run/bmd.sock
Unix domain socket
.It Pa /usr/local/etc/bmd.conf
Configuration file
.It Pa /usr/local/libexec/bmd
Plugin directory
.It Pa /usr/local/var/cache/bmd
Storage for UEFI variables
.El
.Sh SEE ALSO
.Xr bmdctl 8 ,
.Xr bmd.conf 5
