.Dd Apr 8, 2024
.Dt bmdctl 8
.Os
.
.Sh NAME
.Nm bmdctl
.Nd control utility for bhyve management daemon (bmd)
.Sh SYNOPSIS
.Nm
.Op Fl f config_file
.Cm list
.Op Fl r
.Op Fl s Ar colname
.Nm
.Op Fl f config_file
.Cm boot
.Op Fl c 
name
.Nm
.Op Fl f config_file
.Cm install
.Op Fl c
name
.Nm
.Op Fl f config_file
.Cm shutdown
name
.Nm
.Op Fl f config_file
.Cm poweroff
name
.Nm
.Op Fl f config_file
.Cm reset
name
.Nm
.Op Fl f config_file
.Cm console
name
.Nm
.Op Fl f config_file
.Cm showconsole
name
.Nm
.Op Fl f config_file
.Cm showvgaport
name
.Nm
.Op Fl f config_file
.Cm showconfig
.Op name
.Nm
.Op Fl f config_file
.Cm inspect
name
.Nm
.Op Fl f config_file
.Cm run
.Op Fl i
.Op Fl s
name
.Sh DESCRIPTION
The
.Nm
command is a control utility for virtual machines which are managed by
.Xr bmd 8 .
Root privileged user can control all virtual machines. Non-privileged user
can control its own virtual machines.

.Bl -tag -width ".Cm showconsole Fl name"
.It Xo
.Cm list
.Op Fl r
.Op Fl s Ar colname
.Xc
Show list of virtual machines sorted by
.Sq id
column.
.Fl s
option changes the sort key column.
.Fl r
option shows the reverse list.
.It Xo
.Cm boot
.Op Fl c
.Ar name
.Xc
Boot the virtual machine. If
.Fl c
is specified, connect to the console after booting.
.It Xo
.Cm start
.Op Fl c
.Ar name
.Xc
Alias for boot.
.It Xo
.Cm install
.Op Fl c
.Ar name
.Xc
Boot from ISO media to install it. If
.Fl c
is specified, connect to the console after booting.
Note that the installed system never reboots just quits even if user commands
in anyway, reboot the virtual machine manually after shutting down it.
.It Cm shutdown Ar name
Send SIGTERM to the bhyve process to trigger ACPI shutdown.
.It Cm stop Ar name
Alias for shutdown.
.It Cm poweroff Ar name
Force to quit the bhyve process.
.It Cm reset Ar name
Force to reset the bhyve process.
.It Cm console Ar name
Connect to the console of the virtual machine. See ESCAPE SEQUENCES below.
.It Cm showconsole Ar name
Print the console device file. (nmdm)
.It Cm showvgaport Ar name
Print the vnc listen address and port number that are separated by space.
.It Cm showconfig Op Ar name
Parse the configuration file and show virtual machine configurations. This is
for debugging the configuration parser.
.It Cm inspect Ar name
Inspect disks and iso images and show the results for
.Ar loadcmd
and
.Ar installcmd .
.It Xo
.Cm run
.Op Fl i
.Op Fl s
.Ar name
.Xc
Boot the virtual machine directly. The virtual machine runs out of control
from
.Xr bmd 8 .
Root privilege is required. If
.Fl i
is specified, boot from ISO image. If
.Fl s
is specified, boot single user mode.
.El
.Pp
The
.Nm
command connects to the unix domain socket of
.Xr bmd 8
and sends a request of sub-command (excludes the
.Cm run
sub-command). The unix domain
socket path is read from
.Xr bmd.conf 5 .
The file path of
.Xr bmd.conf 5
can be specified
.Fl f
option.
If
.Xr bmd.conf 5
is not readable, use the default path of
.Pa /var/run/bmd.sock .
.Sh ESCAPE SEQUENCES
The following escape sequences are available for
.Nm
.Ic console .
.Bl -tag -width ".Ic ~. No or Ic ~^D"
.It Ic ~. No or Ic ~^D
Drop connection and exit.
.It Ic ~^Z
Stop
.Nm
.Ic console
(only available with job control).
.It Ic ~^Y
Stop only the
.Do
local side
.Dc
of
.Nm
.Ic console
(only available with job control); the
.Do
remote side
.Dc
of
.Nm
.Ic console ,
the side that displays output from the remote host, is left running.
.El
.Sh SEE ALSO
.Xr bmd 8 ,
.Xr bmd.conf 5
